version: '2'
services:
  php-env:
    image: debian:php
    ports:
      - 9000:9000
    volumes:
      - /home/user/Desktop/47/:/usr/share/nginx/html
    container_name: php-env
    #command : ['service php7.0-fpm start']
    stdin_open: true
    tty: true
    #command: /bin/bash
    #restart: always
  service-nginx:
    image: ubuntu:base-ssh
    links:
      - php-env:phpService
    depends_on:
      - php-env
    external_links:
      - nauseous_hopper:test01
    ports:
      - 8087:80
    container_name: service-nginx
    command : ["nginx", "-g", "daemon off;"]
    stdin_open: true
    tty: true

