FROM ubuntu:base

RUN apt-get update && apt-get install -y  python-software-properties \
    add-apt-repository ppa:ondrej/php && \
    apt-get update  && apt-get install\
    php7.1-cli \
    php7.1-common \
    php7.1-curl \
    php7.1-dev \
    php7.1-json \
    php7.1-mbstring \
    php7.1-opcache \
    php7.1-readline \
    php7.1-xml \
    php7.1-zip \
    php7.1-fpm

CMD ["/bin/bash"]

